# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0d632699dad6a5f26503a255c3206e4423e1607c80f04c4b83ac7dfdb7b15bf771cb53fc43f71eb2cac3324bf68178d6d6a28241e88207282f59bc1cf6aa7a7

test:
  secret_key_base: 3069bd1f234df781d4bb7d2eecc4d4f752dc6e0661f031ca18244fadb8250bddacce32051c4c5cf8ad7c69534de2eb8b1f5b2fe3fbedadbd7ff4cd3982c0ba4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
